ADD:flake8 workflows
TISSIS-bc/.github pull request #1
Opened 2022-08-06 14:21 UTC by shiinokinoki

# Description

./workflows/flake8.yml
  - Unified writing style into black.yml

# Context
-  flake8 to run when pull req automatically
# Checklist

- [x] I opened a draft PR or added the `[WIP]` level if my PR is not ready for review.
- [x] I have reviewed the code by myself.
- [x] I have assigned an appropriate reviewer for the PR.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests enough to show how your code behaves and that your code works as expected.

# Additional Notes
A test have been completed.
![image](https://user-images.githubusercontent.com/49639555/183252848-d1cda6ea-99f8-4158-8d28-8a59112b6b2b.png)
![image](https://user-images.githubusercontent.com/49639555/183252862-e76f734a-b153-4157-b7fe-ff021addea0d.png)

2022-08-07 05:06 UTC, terapoon commented
@shiinokinoki 修正しました！確認よろしく

2022-08-07 06:24 UTC, shiinokinoki commented
@terapoon 無事動きました。テスト結果本PRに追記済みです！

2022-08-07 06:27 UTC, shiinokinoki commented
（最後はちゃんとコミットまとめときます）

2022-08-07 06:27 UTC, terapoon commented
@shiinokinoki ありがとう！
上のテストの画像で Flake8 が Fail しているのは想定通りの結果ですか？

2022-08-07 06:33 UTC, shiinokinoki commented
@terapoon 
想定通りです！Flake8に引っかかるコードを食わせたのでErrorとして出力されています。
![image](https://user-images.githubusercontent.com/49639555/183278395-86a1ef35-8164-4a06-a552-0bce5fdd5189.png)


ちなみに綺麗なコードを食わせるとちゃんとSuccessします。
![image](https://user-images.githubusercontent.com/49639555/183278415-f06f4bb2-cd92-41c1-917a-cb9ca8d40617.png)

2022-08-07 06:38 UTC, terapoon requested changes
@shiinokinoki 
GREAT !

1点修正依頼です: github 上（なのかソフトウェア界隈全体でなのかかはわからないけれど）では全てのファイルの末尾に空の行を挿入することが推奨されているという都合があって、file changed を見tもらうと最後の行に警告が出ていることが確認できると思います。
最後の1行を開けるように修正をお願いします !!

ちなみにこの謎のお作法は確か全てのファイルに適用されるはずです。
ファイルの終わりを識別するためとかそういう大義名分があった気がするけど忘れました。

2022-08-13 05:16 UTC, shiinokinoki commented
@terapoon こちらマージお願いします！

2022-08-13 05:17 UTC, terapoon approved these changes
マージを承認します !!

2022-08-13 05:47 UTC, merged